name: Run Unit Tests

on: 
  push:
    branches:
      - main
      - prasant/ci

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v4

      - name: Setup Python 
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -r requirements.txt
      
      - name: Run Tests
        run: |
          source .venv/bin/activate
          which pytest
          echo $MYSECRET
          pytest
